name: flutter_app
description: A new Flutter project.

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.80.0
  ffi: ^2.1.0
  auto_route: ^5.0.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  file_picker: ^5.2.0
  shared_preferences: ^2.0.12
  permission_handler: ^10.2.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^8.0.1
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/app_icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icons/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
